### 抽样分布简介

为了更好地理解抽样分布的概念，让我们先用 python 语言做一些练习。

下面是一个数组，代表我们在之前的视频中看到的学员。其中，1代表喝咖啡的学生，0代表不喝咖啡的学生。

In [73]:
import numpy as np
np.random.seed(42)

students = np.array([1,0,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1,1,1,1,0])

`1.` 计算出上述数组中喝咖啡的学生的比例，并将此值存储在变量 **p** 中。

`2.` 使用 numpy 的 **random.choice** 模拟从 `students` 数组中进行5次取样。喝咖啡学员样本的比例是多少？ 

`3.` 重复上述步骤，再另外获取10,000个比例值，其中每个样本的大小为5。把这些数值存储在 `sample_props` 变量中。

`4.` 这10，000个比例值的平均比例值是多少？该值通常被称为 **抽样分布均值** 。

`5.` 21个原始数据值的方差和标准差分别是多少？

`6.` 你获取的10000个比例值的方差和标准差分别是多少？

`7.` 计算 p(1-p)，你的哪个答案与它最接近？ 

`8.` 计算 p(1-p)/n，你的哪个答案与它最接近？ 

`9.` 需要注意的是， `8.` 中的答案通常被称为 **抽样分布方差** 。如果将第一个样本大小更改为20，最终的抽样分布方差会发生什么变化？ 模拟并重新计算 `6.` 与 `8.` 的答案，检验一下你之前发现的一致性是否仍然成立。

In [74]:
p = students.mean()
p

0.7142857142857143

In [75]:
np.random.choice(students, size=5 )

array([0, 1, 1, 1, 0])

In [76]:
sample_props = np.random.choice(students, size=(10000,5) )
sample_props

array([[0, 0, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0],
       ...,
       [0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [77]:
sample_props.sum(axis=1).mean()

3.57

In [78]:
students.var()

0.20408163265306126

In [79]:
students.std()

0.45175395145262565

In [80]:
sample_props.var()

0.20420400000000002

In [81]:
sample_props.std()

0.45188936699152377

In [82]:
p*(1-p)

0.20408163265306123

In [83]:
#样本为5的分布方差
p*(1-p)/5

0.04081632653061225

In [84]:
#样本wei20的分布方差
p*(1-p)/20

0.010204081632653062

In [85]:
##Simulate your 20 draws
sample_props_20 = np.random.choice(students, size=(10000,20))
sample_props_20

array([[1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 0, 1, 1],
       [0, 1, 0, ..., 1, 0, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 0, 1, 1]])

In [86]:
##Compare your variance values as computed in 6 and 8, 
##but with your sample of 20 values
sample_props_20.var()

0.20380724437499995

In [87]:
sample_props_20.std()

0.45145015713254544

In [88]:
p*(1-p)/10000

2.0408163265306123e-05

`10.` 最后，从样本数量为5的样本和样本数量为20的样本中进行10000次取样，然后绘制一个直方图。这些分布中的每一个都是一个样本分布。 一个是样本量5的比例，另一个是样本量20的样本分布。